# Generated by Django 5.2 on 2025-05-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название города', max_length=50, verbose_name='Название города')),
                ('order', models.SmallIntegerField(db_index=True, default=0, help_text='Порядок города', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['order'],
            },
        ),
    ]
