# Generated by Django 5.2 on 2025-07-09 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Дата')),
                ('total_users', models.PositiveIntegerField(default=0, verbose_name='Всего пользователей')),
                ('new_users', models.PositiveIntegerField(default=0, verbose_name='Новых пользователей')),
                ('active_users', models.PositiveIntegerField(default=0, verbose_name='Активных пользователей')),
                ('total_posts', models.PositiveIntegerField(default=0, verbose_name='Всего объявлений')),
                ('new_posts', models.PositiveIntegerField(default=0, verbose_name='Новых объявлений')),
                ('job_posts', models.PositiveIntegerField(default=0, verbose_name='Вакансий')),
                ('service_posts', models.PositiveIntegerField(default=0, verbose_name='Услуг')),
                ('total_payments', models.PositiveIntegerField(default=0, verbose_name='Всего платежей')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий доход')),
                ('new_payments', models.PositiveIntegerField(default=0, verbose_name='Новых платежей')),
            ],
            options={
                'verbose_name': 'Статистика сайта',
                'verbose_name_plural': 'Статистика сайта',
                'ordering': ['-date'],
            },
        ),
    ]
