# Generated by Django 5.2 on 2025-07-09 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitestatistics',
            name='active_users',
        ),
        migrations.RemoveField(
            model_name='sitestatistics',
            name='job_posts',
        ),
        migrations.RemoveField(
            model_name='sitestatistics',
            name='new_payments',
        ),
        migrations.RemoveField(
            model_name='sitestatistics',
            name='service_posts',
        ),
        migrations.RemoveField(
            model_name='sitestatistics',
            name='total_payments',
        ),
        migrations.RemoveField(
            model_name='sitestatistics',
            name='total_posts',
        ),
        migrations.RemoveField(
            model_name='sitestatistics',
            name='total_users',
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 9, 18, 57, 11, 694093, tzinfo=datetime.timezone.utc), verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitestatistics',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость оплаченных объявлений'),
        ),
    ]
