# Generated by Django 5.2 on 2025-07-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_stats', '0002_remove_sitestatistics_active_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('new_users', models.IntegerField(default=0)),
                ('new_posts', models.IntegerField(default=0)),
                ('post_views', models.IntegerField(default=0)),
                ('favorites_added', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='SiteStatistics',
        ),
    ]
