# Generated by Django 5.2 on 2025-05-15 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ework_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostServices',
            fields=[
                ('abspost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ework_post.abspost')),
            ],
            bases=('ework_post.abspost',),
        ),
        migrations.CreateModel(
            name='ProductViewServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_views', to='ework_services.postservices', verbose_name='Объявление')),
            ],
        ),
    ]
