# Generated by Django 5.2 on 2025-05-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название категории', max_length=200, verbose_name='Название')),
                ('image', models.ImageField(help_text='Изображение для категории', upload_to='category_img/', verbose_name='Изображение')),
                ('order', models.SmallIntegerField(db_index=True, default=0, help_text='Порядок категории', verbose_name='Порядок')),
                ('slug', models.SlugField(help_text='Слаг категории', unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='PostServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название объявления', max_length=200, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание объявления', verbose_name='Описание')),
                ('image', models.ImageField(help_text='Изображение для объявления', upload_to='post_img/', verbose_name='Изображение')),
                ('user_phone', models.CharField(blank=True, help_text='Телефон автора объявления', max_length=20, null=True, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.IntegerField(choices=[(0, 'Не проверено'), (1, 'Одобрено'), (2, 'Отклонено'), (3, 'Опубликовано'), (4, 'Архив')], default=0, verbose_name='Статус')),
                ('is_premium', models.BooleanField(default=False, help_text='Премиум объявление', verbose_name='Премиум')),
                ('price', models.IntegerField(help_text='Цена', verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='ProductViewServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
