# Generated by Django 5.2 on 2025-05-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postservices',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Укажите сумму', max_digits=10, verbose_name='Сумма'),
        ),
    ]
