# Generated by Django 5.2 on 2025-05-14 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ework_services', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postservices',
            name='rubric',
        ),
    ]
