# Generated by Django 5.2 on 2025-05-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postservices',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение для объявления', null=True, upload_to='post_img/', verbose_name='Изображение'),
        ),
    ]
