# Generated by Django 5.2 on 2025-05-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_services', '0003_alter_postservices_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postservices',
            name='user_phone',
            field=models.ImageField(blank=True, help_text='Телефон автора объявления', max_length=13, null=True, upload_to='', verbose_name='Телефон'),
        ),
    ]
