# Generated by Django 5.2 on 2025-05-14 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ework_services', '0003_remove_postservices_rubric'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteServices',
        ),
    ]
