# Generated by Django 5.2 on 2025-06-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ework_services', '0003_delete_productviewservices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostServices',
        ),
    ]
