# Generated by Django 5.2 on 2025-05-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_services', '0004_alter_postservices_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postservices',
            name='price',
            field=models.IntegerField(help_text='Укажите сумму', max_length=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='postservices',
            name='user_phone',
            field=models.IntegerField(blank=True, help_text='Телефон автора объявления', max_length=13, null=True, verbose_name='Телефон'),
        ),
    ]
