# Generated by Django 5.2 on 2025-05-11 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_services', '0006_alter_postservices_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postservices',
            name='user_phone',
            field=models.CharField(blank=True, help_text='Телефон автора объявления', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
    ]
