# Generated by Django 5.2 on 2025-07-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ework_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тарифа', max_length=50, unique=True, verbose_name='Название тарифа')),
                ('description', models.TextField(help_text='Описание тарифа', verbose_name='Описание тарифа')),
                ('package_type', models.CharField(choices=[('FREE_WEEKLY', 'Бесплатная публикация'), ('PAID', 'Платная публикация')], default='FREE_WEEKLY', help_text='Тип пакета', max_length=20, verbose_name='Тип пакета')),
                ('price_per_post', models.DecimalField(decimal_places=2, help_text='Цена за объявление', max_digits=8, verbose_name='Цена за объявление')),
                ('photo_addon_price', models.DecimalField(decimal_places=2, default=0, help_text="Цена аддона 'Фото'", max_digits=8, verbose_name='Цена за фото')),
                ('highlight_addon_price', models.DecimalField(decimal_places=2, default=0, help_text="Цена аддона 'Цветное выделение'", max_digits=8, verbose_name='Цена за выделение')),
                ('auto_bump_addon_price', models.DecimalField(decimal_places=2, default=0, help_text="Цена аддона 'Автоподнятие' (7 дней)", max_digits=8, verbose_name='Цена за автоподнятие')),
                ('highlight_color', models.CharField(blank=True, default='#fffacd', help_text='HEX-код цвета для выделения объявления', max_length=7, verbose_name='HEX-код цвета для выделения объявления')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Срок размещения (дней)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.SmallIntegerField(db_index=True, default=0, help_text='Порядок', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тарифный пакет',
                'verbose_name_plural': 'Тарифные пакеты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='ID заказа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('cancelled', 'Отменено')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('telegram_payment_charge_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа Telegram')),
                ('telegram_provider_payment_charge_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа провайдера')),
                ('addons_data', models.JSONField(blank=True, default=dict, help_text='JSON с информацией о выбранных аддонах', verbose_name='Данные аддонов')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BannerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='ework_premi_is_acti_e07976_idx')],
            },
        ),
        migrations.CreateModel(
            name='FreePostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Дата понедельника этой недели')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ework_post.abspost')),
            ],
            options={
                'verbose_name': 'Бесплатная публикация',
                'verbose_name_plural': 'Бесплатные публикации',
            },
        ),
    ]
