# Generated by Django 5.2 on 2025-05-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreePostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Дата понедельника этой недели')),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тарифа', max_length=50, unique=True, verbose_name='Название тарифа')),
                ('description', models.TextField(help_text='Описание тарифа', verbose_name='Описание тарифа')),
                ('price_per_post', models.DecimalField(decimal_places=2, help_text='Цена за объявление', max_digits=8, verbose_name='Цена за объявление')),
                ('highlight_color', models.CharField(blank=True, help_text='HEX-код цвета для выделения объявления', max_length=7, verbose_name='HEX-код цвета для выделения объявления')),
                ('icon_flag', models.CharField(blank=True, help_text='Имя CSS-класса или значка (например, ⭐️ для Премиум)', max_length=50, verbose_name='Имя CSS-класса или значка (например, ⭐️ для Премиум)')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('remaining_posts', models.PositiveIntegerField(help_text='Сколько постов ещё можно разместить по этому пакету')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
