# Generated by Django 5.2 on 2025-07-21 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ework_config', '0001_initial'),
        ('ework_post', '0002_initial'),
        ('ework_premium', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freepostrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Валюта', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ework_config.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='payment',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ework_premium.package', verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='payment',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Пост-черновик для публикации после оплаты', null=True, on_delete=django.db.models.deletion.CASCADE, to='ework_post.abspost', verbose_name='Пост'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='freepostrecord',
            unique_together={('user', 'week_start')},
        ),
    ]
