# Generated by Django 5.2 on 2025-08-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_premium', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='auto_bump_addon_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Цена аддона 'Автоподнятие'", max_digits=8, verbose_name='Цена за автоподнятие'),
        ),
        migrations.AlterField(
            model_name='package',
            name='highlight_addon_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Цена аддона 'Цветное выделение')", max_digits=8, verbose_name='Цена за выделение'),
        ),
        migrations.AlterField(
            model_name='package',
            name='photo_addon_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Цена аддона 'Фото'", max_digits=8, verbose_name='Цена за фото'),
        ),
    ]
