# Generated by Django 5.2 on 2025-06-18 03:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_post', '0004_postview_alter_bannerpost_options_and_more'),
        ('ework_premium', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freepostrecord',
            options={'verbose_name': 'Бесплатная публикация', 'verbose_name_plural': 'Бесплатные публикации'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['order'], 'verbose_name': 'Тарифный пакет', 'verbose_name_plural': 'Тарифные пакеты'},
        ),
        migrations.RemoveField(
            model_name='freepostrecord',
            name='used',
        ),
        migrations.AddField(
            model_name='freepostrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2025, 6, 18, 3, 36, 45, 966850, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freepostrecord',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ework_post.abspost'),
        ),
        migrations.AddField(
            model_name='package',
            name='allows_photo',
            field=models.BooleanField(default=False, verbose_name='Разрешены фото'),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Срок размещения (дней)'),
        ),
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='package',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=0, help_text='Порядок', verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('FREE_WEEKLY', 'Бесплатная публикация'), ('STANDARD', 'Стандартная публикация'), ('PREMIUM_PHOTO', 'Публикация с фото')], default='FREE_WEEKLY', help_text='Тип пакета', max_length=20, verbose_name='Тип пакета'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('PROCESSING', 'Обрабатывается'), ('COMPLETED', 'Завершена'), ('FAILED', 'Ошибка'), ('CANCELLED', 'Отменена'), ('REFUNDED', 'Возвращена')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('telegram_payment_charge_id', models.CharField(blank=True, max_length=255, verbose_name='Telegram Payment ID')),
                ('provider_payment_charge_id', models.CharField(blank=True, max_length=255, verbose_name='Provider Payment ID')),
                ('invoice_payload', models.TextField(blank=True, verbose_name='Payload инвойса')),
                ('telegram_data', models.JSONField(blank=True, default=dict, verbose_name='Данные от Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ework_premium.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платежная транзакция',
                'verbose_name_plural': 'Платежные транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ework_premium.package')),
                ('payment_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ework_premium.paymenttransaction')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ework_post.abspost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
