# Generated by Django 5.2 on 2025-06-18 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_currency', '0001_initial'),
        ('ework_premium', '0003_alter_freepostrecord_options_alter_package_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Валюта', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ework_currency.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('FREE_WEEKLY', 'Бесплатная публикация'), ('STANDARD', 'Стандартная публикация'), ('PREMIUM_PHOTO', 'Публикация с фото'), ('BANNER', 'Баннер на главной странице'), ('OTHER', 'Другое')], default='FREE_WEEKLY', help_text='Тип пакета', max_length=20, verbose_name='Тип пакета'),
        ),
    ]
