# Generated by Django 5.2 on 2025-06-18 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_premium', '0004_package_currency_alter_package_package_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpayment',
            name='payment_transaction',
        ),
        migrations.RemoveField(
            model_name='postpayment',
            name='package',
        ),
        migrations.RemoveField(
            model_name='postpayment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postpayment',
            name='user',
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('FREE_WEEKLY', 'Бесплатная публикация'), ('PAID', 'Платная публикация')], default='FREE_WEEKLY', help_text='Тип пакета', max_length=20, verbose_name='Тип пакета'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='ID заказа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('cancelled', 'Отменено')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('telegram_payment_charge_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа Telegram')),
                ('telegram_provider_payment_charge_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа провайдера')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ework_premium.package', verbose_name='Тариф')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
        migrations.DeleteModel(
            name='PostPayment',
        ),
    ]
