# Generated by Django 5.2 on 2025-06-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_premium', '0005_remove_postpayment_payment_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='allows_photo',
        ),
        migrations.RemoveField(
            model_name='package',
            name='icon_flag',
        ),
        migrations.AddField(
            model_name='package',
            name='auto_bump_addon_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Цена аддона 'Автоподнятие' (7 дней)", max_digits=8, verbose_name='Цена за автоподнятие'),
        ),
        migrations.AddField(
            model_name='package',
            name='highlight_addon_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Цена аддона 'Цветное выделение' (3 дня)", max_digits=8, verbose_name='Цена за выделение'),
        ),
        migrations.AddField(
            model_name='package',
            name='photo_addon_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Цена аддона 'Фото' (30 дней)", max_digits=8, verbose_name='Цена за фото'),
        ),
        migrations.AddField(
            model_name='payment',
            name='addons_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON с информацией о выбранных аддонах', verbose_name='Данные аддонов'),
        ),
        migrations.AlterField(
            model_name='package',
            name='highlight_color',
            field=models.CharField(blank=True, default='#fffacd', help_text='HEX-код цвета для выделения объявления', max_length=7, verbose_name='HEX-код цвета для выделения объявления'),
        ),
    ]
