# Generated by Django 4.2.13 on 2025-06-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_premium', '0006_remove_package_allows_photo_remove_package_icon_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='post_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON с данными поста для публикации после оплаты', verbose_name='Данные поста'),
        ),
    ]
