# Generated by Django 4.2.13 on 2025-06-27 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ework_post', '0007_alter_abspost_status'),
        ('ework_premium', '0007_payment_post_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='post_data',
        ),
        migrations.AddField(
            model_name='payment',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Пост-черновик для публикации после оплаты', null=True, on_delete=django.db.models.deletion.CASCADE, to='ework_post.abspost', verbose_name='Пост'),
        ),
    ]
