# Generated by Django 5.2 on 2025-06-28 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_config', '0004_city_currency_superrubric_subrubric'),
        ('ework_premium', '0008_remove_payment_post_data_payment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Валюта', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ework_config.currency', verbose_name='Валюта'),
        ),
    ]
