# Generated by Django 5.2 on 2025-06-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_premium', '0009_alter_package_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='ework_premi_is_acti_e07976_idx')],
            },
        ),
    ]
