# Generated by Django 5.2 on 2025-06-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_user_tg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('uk', 'Ukrainian')], default='ru', max_length=10, verbose_name='Язык интерфейса'),
        ),
    ]
