# Generated by Django 4.2.13 on 2025-06-28 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ework_user_tg', '0002_alter_telegramuser_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='rating_count',
        ),
    ]
