# Generated by Django 5.2 on 2025-06-28 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_config', '0004_city_currency_superrubric_subrubric'),
        ('ework_user_tg', '0003_remove_telegramuser_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Город', null=True, on_delete=django.db.models.deletion.PROTECT, to='ework_config.city', verbose_name='Город'),
        ),
    ]
