# Generated by Django 5.2 on 2025-05-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название объявления', max_length=200, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание объявления', verbose_name='Описание')),
                ('image', models.ImageField(help_text='Изображение для объявления', upload_to='post_img/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите сумму', max_digits=10, verbose_name='Сумма')),
                ('user_phone', models.CharField(blank=True, help_text='Телефон автора объявления', max_length=20, null=True, verbose_name='Телефон')),
                ('status', models.IntegerField(choices=[(0, 'Не проверено'), (1, 'Одобрено'), (2, 'Отклонено'), (3, 'Опубликовано'), (4, 'Архив')], default=0, verbose_name='Статус')),
                ('is_premium', models.BooleanField(default=False, help_text='Премиум объявление', verbose_name='Премиум')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('experience', models.IntegerField(choices=[(0, 'Не имеет значения'), (1, 'Нет опыта'), (2, 'От 1 года до 3 лет'), (3, 'От 3 до 6 лет'), (4, 'Более 6 лет')], default=0, verbose_name='Опыт работы')),
                ('work_schedule', models.IntegerField(choices=[(0, '5/2'), (1, '2/2'), (2, '6/1'), (3, '3/3'), (4, 'По выходным'), (5, 'Свободный график'), (6, 'Другое')], default=0, verbose_name='График работы')),
                ('type_of_work', models.IntegerField(choices=[(0, 'Полная занятость'), (1, 'Частичная занятость'), (2, 'Проектная работа'), (3, 'Вахта'), (4, 'Стажировка')], default=0, verbose_name='Тип занятости')),
                ('work_format', models.IntegerField(choices=[(0, 'Офис'), (1, 'Удаленная работа'), (2, 'Гибрид')], default=0, verbose_name='Формат работы')),
            ],
        ),
        migrations.CreateModel(
            name='ProductViewJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
