# Generated by Django 5.2 on 2025-05-15 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ework_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('abspost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ework_post.abspost')),
                ('experience', models.IntegerField(choices=[(0, 'Не имеет значения'), (1, 'Нет опыта'), (2, 'От 1 года до 3 лет'), (3, 'От 3 до 6 лет'), (4, 'Более 6 лет')], default=0, verbose_name='Опыт работы')),
                ('work_schedule', models.IntegerField(choices=[(0, '5/2'), (1, '2/2'), (2, '6/1'), (3, '3/3'), (4, 'По выходным'), (5, 'Свободный график'), (6, 'Другое')], default=0, verbose_name='График работы')),
                ('work_format', models.IntegerField(choices=[(0, 'Офис'), (1, 'Удаленная работа'), (2, 'Гибрид')], default=0, verbose_name='Формат работы')),
            ],
            bases=('ework_post.abspost',),
        ),
        migrations.CreateModel(
            name='ProductViewJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_views', to='ework_job.postjob', verbose_name='Объявление')),
            ],
        ),
    ]
