# Generated by Django 5.2 on 2025-05-05 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ework_job', '0001_initial'),
        ('ework_locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritejob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='postjob',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ework_job.categoryjob', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='postjob',
            name='city',
            field=models.ForeignKey(help_text='Город работы', on_delete=django.db.models.deletion.PROTECT, to='ework_locations.city', verbose_name='Город работы'),
        ),
        migrations.AddField(
            model_name='postjob',
            name='currency',
            field=models.ForeignKey(help_text='Валюта объявления', on_delete=django.db.models.deletion.PROTECT, to='ework_locations.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='postjob',
            name='user',
            field=models.ForeignKey(help_text='Автор объявления', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='favoritejob',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_favorites', to='ework_job.postjob', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='productviewjob',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_views', to='ework_job.postjob', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='productviewjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_views', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
