# Generated by Django 5.2 on 2025-06-16 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ework_job', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductViewJob',
        ),
    ]
