# Generated by Django 5.2 on 2025-05-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_job', '0003_alter_postjob_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='type_of_work',
        ),
        migrations.AlterField(
            model_name='postjob',
            name='experience',
            field=models.IntegerField(choices=[(0, 'Не имеет значения'), (1, 'Нет опыта'), (2, 'От 1 года до 3 лет'), (3, 'От 3 до 6 лет'), (4, 'Более 6 лет')], verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='work_format',
            field=models.IntegerField(choices=[(0, 'Офис'), (1, 'Удаленная работа'), (2, 'Гибрид')], verbose_name='Формат работы'),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='work_schedule',
            field=models.IntegerField(choices=[(0, '5/2'), (1, '2/2'), (2, '6/1'), (3, '3/3'), (4, 'По выходным'), (5, 'Свободный график'), (6, 'Другое')], verbose_name='График работы'),
        ),
    ]
