# Generated by Django 5.2 on 2025-05-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_job', '0005_alter_postjob_experience_alter_postjob_work_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='user_phone',
            field=models.ImageField(blank=True, help_text='Телефон автора объявления', max_length=13, null=True, upload_to='', verbose_name='Телефон'),
        ),
    ]
