# Generated by Django 5.2 on 2025-05-11 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_job', '0007_alter_postjob_price_alter_postjob_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='price',
            field=models.IntegerField(help_text='Укажите сумму', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='user_phone',
            field=models.CharField(blank=True, help_text='Телефон автора объявления', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр разрешено.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
    ]
