# Generated by Django 5.2 on 2025-05-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название валюты', max_length=20, verbose_name='Название')),
                ('code', models.CharField(db_index=True, help_text='Код валюты', max_length=8, verbose_name='Код')),
                ('order', models.SmallIntegerField(db_index=True, default=0, help_text='Порядок валюты', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['order'],
            },
        ),
    ]
