# Generated by Django 4.2.13 on 2025-06-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='$', help_text='Символ валюты', max_length=5, verbose_name='Символ'),
        ),
    ]
