# Generated by Django 5.2 on 2025-06-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_currency', '0002_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='₴', help_text='Символ валюты', max_length=5, verbose_name='Символ'),
        ),
    ]
