# Generated by Django 5.2 on 2025-06-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ework_currency', '0003_alter_currency_symbol'),
        ('ework_post', '0011_postjob_postservices_alter_abspost_city_and_more'),
        ('ework_premium', '0009_alter_package_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
