# Generated by Django 5.2 on 2025-07-22 02:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ework_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
                ('description', models.TextField(db_index=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_img/', verbose_name='Изображение')),
                ('price', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)], verbose_name='Сумма')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+3(xxx)xxx-xx-xx'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('status', models.IntegerField(choices=[(-1, 'Черновик'), (0, 'Не проверено'), (1, 'На модерации'), (2, 'Отклонено'), (3, 'Опубликовано'), (4, 'Архив')], db_index=True, default=0, verbose_name='Статус')),
                ('is_premium', models.BooleanField(db_index=True, default=False, verbose_name='Цветной фон карточки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('has_photo_addon', models.BooleanField(default=False, verbose_name='Аддон фото')),
                ('has_highlight_addon', models.BooleanField(default=False, verbose_name='Аддон выделения')),
                ('has_auto_bump_addon', models.BooleanField(default=False, verbose_name='Аддон автоподнятия')),
                ('highlight_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Выделение до')),
                ('auto_bump_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Автоподнятие до')),
                ('last_bump_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее поднятие')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ework_config.city', verbose_name='Город работы')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ework_config.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
            ],
            options={
                'verbose_name': 'Просмотр',
                'verbose_name_plural': 'Просмотры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('abspost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ework_post.abspost')),
                ('experience', models.IntegerField(choices=[(0, 'Не имеет значения'), (1, 'Нет опыта'), (2, 'От 1 года до 3 лет'), (3, 'От 3 до 6 лет'), (4, 'Более 6 лет')], default=0, verbose_name='Опыт работы')),
                ('work_schedule', models.IntegerField(choices=[(0, '5/2'), (1, '2/2'), (2, '6/1'), (3, '3/3'), (4, 'По выходным'), (5, 'Свободный график'), (6, 'Другое')], default=0, verbose_name='График работы')),
                ('work_format', models.IntegerField(choices=[(0, 'Офис'), (1, 'Удаленная работа'), (2, 'Гибрид')], default=0, verbose_name='Формат работы')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
            bases=('ework_post.abspost',),
        ),
        migrations.CreateModel(
            name='PostServices',
            fields=[
                ('abspost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ework_post.abspost')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
            bases=('ework_post.abspost',),
        ),
    ]
