# Generated by Django 5.2 on 2025-05-15 12:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ework_currency', '0001_initial'),
        ('ework_locations', '0001_initial'),
        ('ework_rubric', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AbsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название объявления', max_length=200, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание объявления', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Изображение для объявления', null=True, upload_to='post_img/', verbose_name='Изображение')),
                ('price', models.IntegerField(help_text='Укажите сумму', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)], verbose_name='Сумма')),
                ('user_phone', models.CharField(blank=True, help_text='Телефон автора объявления', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('status', models.IntegerField(choices=[(0, 'Не проверено'), (1, 'Одобрено'), (2, 'Отклонено'), (3, 'Опубликовано'), (4, 'Архив')], default=0, verbose_name='Статус')),
                ('is_premium', models.BooleanField(default=False, help_text='Премиум объявление', verbose_name='Премиум')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('city', models.ForeignKey(help_text='Город работы', on_delete=django.db.models.deletion.PROTECT, to='ework_locations.city', verbose_name='Город работы')),
                ('currency', models.ForeignKey(help_text='Валюта объявления', on_delete=django.db.models.deletion.PROTECT, to='ework_currency.currency', verbose_name='Валюта')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('sub_rubric', models.ForeignKey(help_text='Рубрика объявления', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_products', to='ework_rubric.subrubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
    ]
