# Generated by Django 5.2 on 2025-07-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ework_config', '0001_initial'),
        ('ework_post', '0001_initial'),
        ('ework_premium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abspost',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ework_premium.package', verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='abspost',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='abspost',
            name='sub_rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_posts', to='ework_config.subrubric', verbose_name='Рубрика'),
        ),
    ]
