# Generated by Django 5.2 on 2025-07-21 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ework_post', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abspost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='ework_post.abspost', verbose_name='Пост'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='postview',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента'),
        ),
        migrations.AddField(
            model_name='postview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='abspost',
            index=models.Index(fields=['status', 'created_at'], name='ework_post__status_6ddb22_idx'),
        ),
        migrations.AddIndex(
            model_name='abspost',
            index=models.Index(fields=['sub_rubric', 'status'], name='ework_post__sub_rub_bb7396_idx'),
        ),
        migrations.AddIndex(
            model_name='abspost',
            index=models.Index(fields=['city', 'status'], name='ework_post__city_id_834448_idx'),
        ),
        migrations.AddIndex(
            model_name='abspost',
            index=models.Index(fields=['user', 'status'], name='ework_post__user_id_63eac4_idx'),
        ),
        migrations.AddIndex(
            model_name='abspost',
            index=models.Index(fields=['is_premium', 'status', 'created_at'], name='ework_post__is_prem_03f162_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'created_at'], name='ework_post__user_id_8dec28_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['post', 'created_at'], name='ework_post__post_id_8a1580_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_favorite'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['content_type', 'object_id'], name='ework_post__content_c0ed6a_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['user', 'created_at'], name='ework_post__user_id_c5980f_idx'),
        ),
        migrations.AddConstraint(
            model_name='postview',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_user_post_view'),
        ),
    ]
