# Generated by Django 5.2 on 2025-08-09 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_config', '0002_alter_siteconfig_site_name'),
        ('ework_post', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abspost',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ework_config.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='work_format',
            field=models.IntegerField(choices=[(0, 'Офис'), (1, 'Удаленная работа'), (2, 'Гибрид'), (3, 'Вахта'), (4, 'Другое')], default=0, verbose_name='Формат работы'),
        ),
    ]
