# Generated by Django 5.2 on 2025-07-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_post', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='work_format',
            field=models.IntegerField(choices=[(0, 'Офис'), (1, 'Удаленная работа'), (2, 'Гибрид'), (3, 'Вахта'), (4, 'Другое')], default=0, verbose_name='Формат работы'),
        ),
    ]
