# Generated by Django 5.2 on 2025-06-16 23:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ework_currency', '0001_initial'),
        ('ework_locations', '0001_initial'),
        ('ework_post', '0003_bannerpost_alter_abspost_title'),
        ('ework_rubric', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
            ],
            options={
                'verbose_name': 'Просмотр',
                'verbose_name_plural': 'Просмотры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='bannerpost',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='abspost',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='abspost',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Мягкое удаление', verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='bannerpost',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='description',
            field=models.TextField(db_index=True, help_text='Описание объявления', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, help_text='Премиум объявление', verbose_name='Премиум'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='price',
            field=models.IntegerField(db_index=True, help_text='Укажите сумму', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не проверено'), (1, 'Одобрено'), (2, 'Отклонено'), (3, 'Опубликовано'), (4, 'Архив')], db_index=True, default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='sub_rubric',
            field=models.ForeignKey(help_text='Рубрика объявления', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_posts', to='ework_rubric.subrubric', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='title',
            field=models.CharField(db_index=True, help_text='Название объявления', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='user_phone',
            field=models.CharField(blank=True, help_text='Телефон автора объявления', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+7(xxx)xxx-xx-xx'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='bannerpost',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='ework_post.abspost', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='abspost',
            index=models.Index(fields=['status', 'created_at'], name='ework_post__status_6ddb22_idx'),
        ),
        migrations.AddIndex(
            model_name='abspost',
            index=models.Index(fields=['sub_rubric', 'status'], name='ework_post__sub_rub_bb7396_idx'),
        ),
        migrations.AddIndex(
            model_name='abspost',
            index=models.Index(fields=['city', 'status'], name='ework_post__city_id_834448_idx'),
        ),
        migrations.AddIndex(
            model_name='abspost',
            index=models.Index(fields=['user', 'status'], name='ework_post__user_id_63eac4_idx'),
        ),
        migrations.AddIndex(
            model_name='abspost',
            index=models.Index(fields=['is_premium', 'status', 'created_at'], name='ework_post__is_prem_03f162_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerpost',
            index=models.Index(fields=['is_active', 'order'], name='ework_post__is_acti_d0c413_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'created_at'], name='ework_post__user_id_8dec28_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['post', 'created_at'], name='ework_post__post_id_8a1580_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_favorite'),
        ),
        migrations.AddField(
            model_name='postview',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента'),
        ),
        migrations.AddField(
            model_name='postview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['content_type', 'object_id'], name='ework_post__content_c0ed6a_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['user', 'created_at'], name='ework_post__user_id_c5980f_idx'),
        ),
        migrations.AddConstraint(
            model_name='postview',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_user_post_view'),
        ),
    ]
