# Generated by Django 5.2 on 2025-06-18 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_post', '0004_postview_alter_bannerpost_options_and_more'),
        ('ework_premium', '0005_remove_postpayment_payment_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abspost',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Тариф объявления', null=True, on_delete=django.db.models.deletion.PROTECT, to='ework_premium.package', verbose_name='Тариф'),
        ),
    ]
