# Generated by Django 5.2 on 2025-08-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ework_post', '0004_alter_abspost_city_alter_postjob_work_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abspost',
            name='auto_bump_expires_at',
        ),
        migrations.RemoveField(
            model_name='abspost',
            name='has_auto_bump_addon',
        ),
        migrations.RemoveField(
            model_name='abspost',
            name='highlight_expires_at',
        ),
        migrations.RemoveField(
            model_name='abspost',
            name='last_bump_at',
        ),
    ]
