# Generated by Django 5.2 on 2025-08-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ework_post', '0005_remove_abspost_auto_bump_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abspost',
            name='has_highlight_addon',
        ),
    ]
