# Generated by Django 5.2 on 2025-06-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_post', '0005_abspost_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='abspost',
            name='auto_bump_expires_at',
            field=models.DateTimeField(blank=True, help_text='Дата окончания автоподнятия', null=True, verbose_name='Автоподнятие до'),
        ),
        migrations.AddField(
            model_name='abspost',
            name='has_auto_bump_addon',
            field=models.BooleanField(default=False, help_text='Автоматическое поднятие в топ', verbose_name='Аддон автоподнятия'),
        ),
        migrations.AddField(
            model_name='abspost',
            name='has_highlight_addon',
            field=models.BooleanField(default=False, help_text='Пост выделяется цветом', verbose_name='Аддон выделения'),
        ),
        migrations.AddField(
            model_name='abspost',
            name='has_photo_addon',
            field=models.BooleanField(default=False, help_text='Разрешено добавлять фото', verbose_name='Аддон фото'),
        ),
        migrations.AddField(
            model_name='abspost',
            name='highlight_expires_at',
            field=models.DateTimeField(blank=True, help_text='Дата окончания выделения', null=True, verbose_name='Выделение до'),
        ),
        migrations.AddField(
            model_name='abspost',
            name='last_bump_at',
            field=models.DateTimeField(blank=True, help_text='Дата последнего автоподнятия', null=True, verbose_name='Последнее поднятие'),
        ),
    ]
