# Generated by Django 4.2.13 on 2025-06-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_post', '0006_abspost_auto_bump_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abspost',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Черновик'), (0, 'Не проверено'), (1, 'Одобрено'), (2, 'Отклонено'), (3, 'Опубликовано'), (4, 'Архив')], db_index=True, default=0, verbose_name='Статус'),
        ),
    ]
