# Generated by Django 4.2.13 on 2025-06-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_post', '0007_alter_abspost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abspost',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Черновик'), (0, 'Не проверено'), (1, 'На модерации'), (2, 'Отклонено'), (3, 'Ожидает ручного одобрения'), (4, 'Опубликовано'), (5, 'Архив')], db_index=True, default=0, verbose_name='Статус'),
        ),
    ]
