# Generated by Django 5.2 on 2025-06-28 14:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_currency', '0002_currency_symbol'),
        ('ework_locations', '0001_initial'),
        ('ework_post', '0009_alter_abspost_status'),
        ('ework_premium', '0008_remove_payment_post_data_payment_post'),
        ('ework_rubric', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='abspost',
            name='auto_bump_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Автоподнятие до'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ework_locations.city', verbose_name='Город работы'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ework_currency.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='description',
            field=models.TextField(db_index=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='has_auto_bump_addon',
            field=models.BooleanField(default=False, verbose_name='Аддон автоподнятия'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='has_highlight_addon',
            field=models.BooleanField(default=False, verbose_name='Аддон выделения'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='has_photo_addon',
            field=models.BooleanField(default=False, verbose_name='Аддон фото'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='highlight_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Выделение до'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_img/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Премиум'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='last_bump_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее поднятие'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ework_premium.package', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='price',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='sub_rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_posts', to='ework_rubric.subrubric', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+7(xxx)xxx-xx-xx'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='bannerpost',
            name='image',
            field=models.ImageField(upload_to='banner/', verbose_name='Изображение'),
        ),
    ]
