# Generated by Django 5.2 on 2025-06-28 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_config', '0004_city_currency_superrubric_subrubric'),
        ('ework_post', '0010_alter_abspost_auto_bump_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('abspost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ework_post.abspost')),
                ('experience', models.IntegerField(choices=[(0, 'Не имеет значения'), (1, 'Нет опыта'), (2, 'От 1 года до 3 лет'), (3, 'От 3 до 6 лет'), (4, 'Более 6 лет')], default=0, verbose_name='Опыт работы')),
                ('work_schedule', models.IntegerField(choices=[(0, '5/2'), (1, '2/2'), (2, '6/1'), (3, '3/3'), (4, 'По выходным'), (5, 'Свободный график'), (6, 'Другое')], default=0, verbose_name='График работы')),
                ('work_format', models.IntegerField(choices=[(0, 'Офис'), (1, 'Удаленная работа'), (2, 'Гибрид')], default=0, verbose_name='Формат работы')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
            bases=('ework_post.abspost',),
        ),
        migrations.CreateModel(
            name='PostServices',
            fields=[
                ('abspost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ework_post.abspost')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
            bases=('ework_post.abspost',),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ework_config.city', verbose_name='Город работы'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ework_config.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='sub_rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_posts', to='ework_config.subrubric', verbose_name='Рубрика'),
        ),
    ]
