# Generated by Django 5.2 on 2025-06-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ework_post', '0011_postjob_postservices_alter_abspost_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerPost',
        ),
    ]
