# Generated by Django 5.2 on 2025-06-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_post', '0012_delete_bannerpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abspost',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Цветной фон карточки'),
        ),
    ]
