# Generated by Django 5.2 on 2025-07-04 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_post', '0013_alter_abspost_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='abspost',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='abspost',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+3(xxx)xxx-xx-xx'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
    ]
