# Generated by Django 5.2 on 2025-07-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_post', '0014_abspost_address_alter_abspost_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abspost',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Черновик'), (0, 'Не проверено'), (1, 'На модерации'), (2, 'Отклонено'), (3, 'Опубликовано'), (4, 'Архив'), (5, 'Удален')], db_index=True, default=0, verbose_name='Статус'),
        ),
    ]
