# Generated by Django 5.2 on 2025-07-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ework_post", "0014_abspost_address_alter_abspost_user_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abspost",
            name="auto_bump_expires_at",
        ),
        migrations.RemoveField(
            model_name="abspost",
            name="has_auto_bump_addon",
        ),
        migrations.RemoveField(
            model_name="abspost",
            name="last_bump_at",
        ),
        migrations.AddField(
            model_name="abspost",
            name="photo_expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Фото до"),
        ),
    ]
