# Generated by Django 5.2 on 2025-05-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название подрубрики', max_length=30, verbose_name='Название')),
                ('image', models.ImageField(help_text='Изображение для подрубрики', upload_to='sub_rubric_img/', verbose_name='Изображение')),
                ('slug', models.SlugField(help_text='Слаг подрубрики', unique=True, verbose_name='Слаг')),
                ('order', models.SmallIntegerField(db_index=True, default=0, help_text='Порядок подрубрики', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Подрубрика',
                'verbose_name_plural': 'Subcategories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SuperRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название рубрики', max_length=30, verbose_name='Название')),
                ('image', models.ImageField(help_text='Изображение для рубрики', upload_to='rubric_img/', verbose_name='Изображение')),
                ('slug', models.SlugField(help_text='Слаг рубрики', unique=True, verbose_name='Слаг')),
                ('order', models.SmallIntegerField(db_index=True, default=0, help_text='Порядок рубрики', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
    ]
