# Generated by Django 5.2 on 2025-05-08 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название рубрики', max_length=30, verbose_name='Название')),
                ('image', models.ImageField(help_text='Изображение для рубрики', upload_to='rubric_img/', verbose_name='Изображение')),
                ('slug', models.SlugField(help_text='Слаг рубрики', unique=True, verbose_name='Слаг')),
                ('order', models.SmallIntegerField(db_index=True, default=0, help_text='Порядок рубрики', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubRubric',
            fields=[
            ],
            options={
                'verbose_name': 'Подрубрика',
                'verbose_name_plural': 'Подрубрики',
                'ordering': ('super_rubric__order', 'super_rubric__name', 'order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ework_rubric.rubric',),
        ),
        migrations.CreateModel(
            name='SuperRubric',
            fields=[
            ],
            options={
                'verbose_name': 'Суперрубрика',
                'verbose_name_plural': 'Суперрубрики',
                'ordering': ('order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ework_rubric.rubric',),
        ),
        migrations.AddField(
            model_name='rubric',
            name='super_rubric',
            field=models.ForeignKey(blank=True, help_text='Родительская рубрика', null=True, on_delete=django.db.models.deletion.PROTECT, to='ework_rubric.superrubric', verbose_name='Родительская рубрика'),
        ),
    ]
