# Generated by Django 5.2 on 2025-06-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ework_post', '0011_postjob_postservices_alter_abspost_city_and_more'),
        ('ework_rubric', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubRubric',
        ),
        migrations.DeleteModel(
            name='SuperRubric',
        ),
    ]
