# Generated by Django 5.2 on 2025-05-14 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_rubric', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subrubric',
            options={'ordering': ['order'], 'verbose_name': 'Подрубрика', 'verbose_name_plural': 'Подрубрики'},
        ),
        migrations.AlterModelOptions(
            name='superrubric',
            options={'ordering': ['order'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='subrubric',
            name='super_rubric',
            field=models.ForeignKey(default=1, help_text='Категория подрубрики', on_delete=django.db.models.deletion.PROTECT, related_name='sub_rubrics', to='ework_rubric.superrubric', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
