# Generated by Django 5.2 on 2025-07-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, 'Київ'), (1, 'Дніпро'), (2, 'Хмельницький'), (3, 'Миколаїв'), (4, 'Вінниця'), (5, 'Харків'), (6, 'Одеса'), (7, 'Запоріжжя'), (8, 'Львів'), (9, 'Полтава'), (10, 'Житомир'), (11, 'Інше')], default=0, verbose_name='Название города')),
                ('order', models.SmallIntegerField(db_index=True, default=0, help_text='Порядок города', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название валюты', max_length=20, verbose_name='Название')),
                ('code', models.CharField(db_index=True, help_text='Код валюты', max_length=8, verbose_name='Код')),
                ('symbol', models.CharField(default='₴', help_text='Символ валюты', max_length=5, verbose_name='Символ')),
                ('order', models.SmallIntegerField(db_index=True, default=0, help_text='Порядок валюты', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='eWork', max_length=200, verbose_name='Название')),
                ('site_description', models.TextField(default='Платформа для поиска работы и услуг', verbose_name='Приветственное  сообщение для бота')),
                ('site_url', models.URLField(default='https://helpwork.com.ua', verbose_name='URL сайта для Мини Апп')),
                ('bot_token', models.CharField(blank=True, max_length=200, verbose_name='Bot Token')),
                ('bot_username', models.CharField(blank=True, max_length=100, verbose_name='Bot Username')),
                ('notification_bot_token', models.CharField(blank=True, max_length=200, verbose_name='Support Bot Token')),
                ('admin_chat_id', models.CharField(blank=True, max_length=20, verbose_name='Admin Chat ID')),
                ('admin_username', models.CharField(blank=True, max_length=20, verbose_name='Admin Username')),
                ('payment_provider_token', models.CharField(blank=True, max_length=200, verbose_name='Payment Provider Token')),
                ('mistral_api_key', models.CharField(blank=True, max_length=200, verbose_name='Mistral API Key')),
                ('auto_moderation_enabled', models.BooleanField(default=True, help_text='Использовать ИИ для автоматической проверки постов', verbose_name='Автоматическая модерация включена')),
                ('manual_approval_required', models.BooleanField(default=False, help_text='Даже после ИИ модерации требуется ручное одобрение админом', verbose_name='Требуется ручное одобрение')),
                ('max_free_posts_per_user', models.PositiveIntegerField(default=1, verbose_name='Максимум бесплатных постов на пользователя')),
                ('post_expiry_days', models.PositiveIntegerField(default=30, verbose_name='Дни до истечения поста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Конфигурация сайта',
                'verbose_name_plural': 'Конфигурация сайта',
            },
        ),
        migrations.CreateModel(
            name='SuperRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название рубрики', max_length=30, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Слаг рубрики', unique=True, verbose_name='Слаг')),
                ('order', models.SmallIntegerField(db_index=True, default=0, help_text='Порядок рубрики', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название подрубрики', max_length=30, verbose_name='Название')),
                ('icon', models.ImageField(blank=True, help_text='Иконка подрубрики', null=True, upload_to='icons', verbose_name='Иконка')),
                ('slug', models.SlugField(blank=True, help_text='Слаг подрубрики', null=True, unique=True, verbose_name='Слаг')),
                ('order', models.SmallIntegerField(db_index=True, default=0, help_text='Порядок подрубрики', verbose_name='Порядок')),
                ('super_rubric', models.ForeignKey(help_text='Категория подрубрики', on_delete=django.db.models.deletion.PROTECT, related_name='sub_rubrics', to='ework_config.superrubric', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подрубрика',
                'verbose_name_plural': 'Подрубрики',
                'ordering': ['order'],
            },
        ),
    ]
