# Generated by Django 5.2 on 2025-08-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name',
            field=models.CharField(default='Help Work', max_length=200, verbose_name='Название сайта'),
        ),
    ]
