# Generated by Django 5.2 on 2025-07-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrubric',
            name='slug',
            field=models.SlugField(blank=True, help_text='Слаг подрубрики', null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
