# Generated by Django 4.2.13 on 2025-06-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='auto_moderation_enabled',
            field=models.BooleanField(default=True, help_text='Использовать ИИ для автоматической проверки постов', verbose_name='Автоматическая модерация включена'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='manual_approval_required',
            field=models.BooleanField(default=False, help_text='Даже после ИИ модерации требуется ручное одобрение админом', verbose_name='Требуется ручное одобрение'),
        ),
    ]
