# Generated by Django 5.2 on 2025-07-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_config', '0002_alter_subrubric_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.IntegerField(choices=[(0, 'Київ'), (1, 'Дніпро'), (2, 'Хмельницький'), (3, 'Миколаїв'), (4, 'Вінниця'), (5, 'Харків'), (6, 'Одеса'), (7, 'Запоріжжя'), (8, 'Львів'), (9, 'Полтава'), (10, 'Житомир'), (11, 'Інше')], default=0, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_url',
            field=models.URLField(default='https://helpwork.com.ua', verbose_name='URL сайта для Мини Апп'),
        ),
    ]
