# Generated by Django 5.2 on 2025-06-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_config', '0002_alter_siteconfig_auto_moderation_enabled_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='SystemLog',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='debug_mode',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='maintenance_mode',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='min_rating_to_post',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='support_email',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='telegram_channel',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='telegram_group',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='admin_username',
            field=models.CharField(blank=True, max_length=20, verbose_name='Admin Username'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='admin_chat_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Admin Chat ID'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='max_free_posts_per_user',
            field=models.PositiveIntegerField(default=1, verbose_name='Максимум бесплатных постов на пользователя'),
        ),
    ]
