# Generated by Django 5.2 on 2025-08-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_config', '0002_alter_siteconfig_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subrubric',
            name='name_ru',
            field=models.CharField(db_index=True, help_text='Название подрубрики', max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='subrubric',
            name='name_uk',
            field=models.CharField(db_index=True, help_text='Название подрубрики', max_length=30, null=True, verbose_name='Название'),
        ),
    ]
