# Generated by Django 5.2 on 2025-06-28 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_config', '0003_delete_adminuser_delete_systemlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название города', max_length=50, verbose_name='Название города')),
                ('order', models.SmallIntegerField(db_index=True, default=0, help_text='Порядок города', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название валюты', max_length=20, verbose_name='Название')),
                ('code', models.CharField(db_index=True, help_text='Код валюты', max_length=8, verbose_name='Код')),
                ('symbol', models.CharField(default='₴', help_text='Символ валюты', max_length=5, verbose_name='Символ')),
                ('order', models.SmallIntegerField(db_index=True, default=0, help_text='Порядок валюты', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SuperRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название рубрики', max_length=30, verbose_name='Название')),
                ('image', models.ImageField(help_text='Изображение для рубрики', upload_to='rubric_img/', verbose_name='Изображение')),
                ('slug', models.SlugField(help_text='Слаг рубрики', unique=True, verbose_name='Слаг')),
                ('order', models.SmallIntegerField(db_index=True, default=0, help_text='Порядок рубрики', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название подрубрики', max_length=30, verbose_name='Название')),
                ('image', models.ImageField(help_text='Изображение для подрубрики', upload_to='sub_rubric_img/', verbose_name='Изображение')),
                ('slug', models.SlugField(help_text='Слаг подрубрики', unique=True, verbose_name='Слаг')),
                ('order', models.SmallIntegerField(db_index=True, default=0, help_text='Порядок подрубрики', verbose_name='Порядок')),
                ('super_rubric', models.ForeignKey(help_text='Категория подрубрики', on_delete=django.db.models.deletion.PROTECT, related_name='sub_rubrics', to='ework_config.superrubric', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подрубрика',
                'verbose_name_plural': 'Подрубрики',
                'ordering': ['order'],
            },
        ),
    ]
