# Generated by Django 5.2 on 2025-08-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_config', '0003_subrubric_name_ru_subrubric_name_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(db_index=True, help_text='Название города', max_length=50, null=True, verbose_name='Название города'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_uk',
            field=models.CharField(db_index=True, help_text='Название города', max_length=50, null=True, verbose_name='Название города'),
        ),
    ]
