# Generated by Django 5.2 on 2025-06-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ework_config', '0004_city_currency_superrubric_subrubric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subrubric',
            name='image',
        ),
        migrations.RemoveField(
            model_name='superrubric',
            name='image',
        ),
    ]
