# Generated by Django 5.2 on 2025-08-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_config', '0004_city_name_ru_city_name_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='chat_id',
            field=models.BigIntegerField(blank=True, help_text='Чат города', null=True, verbose_name='Чат города'),
        ),
    ]
