# Generated by Django 5.2 on 2025-06-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_config', '0005_remove_subrubric_image_remove_superrubric_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='notification_bot_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='Support Bot Token'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_description',
            field=models.TextField(default='Платформа для поиска работы и услуг', verbose_name='Приветственное  сообщение для бота'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name',
            field=models.CharField(default='eWork', max_length=200, verbose_name='Текст для кнопки'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_url',
            field=models.URLField(default='https://localhost:8000', verbose_name='URL сайта для Мини Апп'),
        ),
    ]
