# Generated by Django 5.2 on 2025-07-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ework_config', '0006_alter_siteconfig_notification_bot_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subrubric',
            name='icon',
            field=models.ImageField(blank=True, help_text='Иконка подрубрики', null=True, upload_to='icons', verbose_name='Иконка'),
        ),
    ]
