# Generated by Django 5.2 on 2025-07-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ework_config", "0007_subrubric_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="highlight_addon_duration_days",
            field=models.PositiveIntegerField(
                default=3, verbose_name='Длительность услуги "Цвет фона" (дней)'
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="photo_addon_duration_days",
            field=models.PositiveIntegerField(
                default=30, verbose_name='Длительность услуги "Фото" (дней)'
            ),
        ),
    ]
